### ISSUE TITLE
ts: use top level await

### ISSUE THREAD

**Issue by AlexAegis** [AlexAegis/advent-of-code#68]

**Comment by adaamz** [comment]
deno? :)

**Comment by AlexAegis** [comment]
I did already consider it (As I barely use 3pp packages, and this isnt published either), but that would require me to redo all the imports everywhere, so maybe next year

**Comment by adaamz** [comment]
I think eslint is included in `deno fmt`.

Yeah imports are annoying, but more annoying is lack of IDE support :-/

**Comment by AlexAegis** [comment]
Also, me using top level await is currently blocked by ts-node and ts paths (which I can actually omit by using npm7 workspaces) but yeah deno would solve it.
