### ISSUE TITLE
how long takes day 15?

### ISSUE THREAD

**Issue by adaamz** [AlexAegis/advent-of-code#72]
Hi,
I see you have also long run on day 15 with 30M iterations. How long does it run on your machine?
[Mine](https://github.com/adaamz/advent-of-code-2020/tree/main/15/src) run 
- 6 minutes on node
- 2,5 minutes on deno
- 15s on python
- 4,5s on php
It looks really strange that js is so slow compared to other languages.

**Comment by AlexAegis** [comment]
Hello, you can see my benchmarks in the main readme file and as a comment in each task script. On a i7 8700k it takes 5 seconds (nodejs)

**Comment by adaamz** [comment]
right, overlooked that this time :) thx!
btw must check your solution and why is my so slow on node then :)

**Comment by adaamz** [comment]
ok, awesome... I changed object to Map and it really runs only 5s! I will use it in future as well, tyvm again!
